### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by coletdjnz** [deedy5/primp#28]
Hi, would you be open to adding a license to this project?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

I notice it says MIT in [pyproject.toml](https://github.com/deedy5/pyreqwest_impersonate/blob/main/pyproject.toml), perhaps add it as a LICENSE file?

thanks :smiley:

**Comment by deedy5** [comment]
Hi.
Done.
https://github.com/deedy5/primp/blob/main/LICENSE
