### ISSUE TITLE
Build errors (boring-sys-imp-4.9.1)

### ISSUE THREAD

**Issue by okeyzero** [deedy5/primp#32]
error: failed to run custom build command for `boring-sys-imp v4.9.1`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused by:

**Comment by deedy5** [comment]
what's the question?

**Comment by okeyzero** [comment]
> what's the question?

error: failed to run custom build command for `boring-sys-imp v4.9.3`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused by:
  process didn't exit successfully: `/Users/user/RustroverProjects/primp/target/debug/build/boring-sys-imp-38c2fc35e7f17890/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=BORING_BSSL_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=BORING_BSSL_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_BORING_BSSL_PATH
  cargo:rerun-if-env-changed=BORING_BSSL_PATH
  cargo:rerun-if-env-changed=BORING_BSSL_INCLUDE_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=BORING_BSSL_INCLUDE_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_BORING_BSSL_INCLUDE_PATH
  cargo:rerun-if-env-changed=BORING_BSSL_INCLUDE_PATH
  cargo:rerun-if-env-changed=BORING_BSSL_SOURCE_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=BORING_BSSL_SOURCE_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_BORING_BSSL_SOURCE_PATH
  cargo:rerun-if-env-changed=BORING_BSSL_SOURCE_PATH
  cargo:rerun-if-env-changed=BORING_BSSL_PRECOMPILED_BCM_O_aarch64-apple-darwin
  cargo:rerun-if-env-changed=BORING_BSSL_PRECOMPILED_BCM_O_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_BORING_BSSL_PRECOMPILED_BCM_O
  cargo:rerun-if-env-changed=BORING_BSSL_PRECOMPILED_BCM_O
  cargo:rerun-if-env-changed=BORING_BSSL_ASSUME_PATCHED_aarch64-apple-darwin
  cargo:rerun-if-env-changed=BORING_BSSL_ASSUME_PATCHED_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_BORING_BSSL_ASSUME_PATCHED
  cargo:rerun-if-env-changed=BORING_BSSL_ASSUME_PATCHED
  cargo:rerun-if-env-changed=BORING_BSSL_SYSROOT_aarch64-apple-darwin
  cargo:rerun-if-env-changed=BORING_BSSL_SYSROOT_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_BORING_BSSL_SYSROOT
  cargo:rerun-if-env-changed=BORING_BSSL_SYSROOT
  cargo:rerun-if-env-changed=BORING_BSSL_COMPILER_EXTERNAL_TOOLCHAIN_aarch64-apple-darwin
  cargo:rerun-if-env-changed=BORING_BSSL_COMPILER_EXTERNAL_TOOLCHAIN_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_BORING_BSSL_COMPILER_EXTERNAL_TOOLCHAIN
  cargo:rerun-if-env-changed=BORING_BSSL_COMPILER_EXTERNAL_TOOLCHAIN
  cargo:rerun-if-env-changed=DEBUG_aarch64-apple-darwin
  cargo:rerun-if-env-changed=DEBUG_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_DEBUG
  cargo:rerun-if-env-changed=DEBUG
  cargo:rerun-if-env-changed=OPT_LEVEL_aarch64-apple-darwin
  cargo:rerun-if-env-changed=OPT_LEVEL_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_OPT_LEVEL
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=ANDROID_NDK_HOME_aarch64-apple-darwin
  cargo:rerun-if-env-changed=ANDROID_NDK_HOME_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_ANDROID_NDK_HOME
  cargo:rerun-if-env-changed=ANDROID_NDK_HOME
  cargo:rerun-if-env-changed=CMAKE_TOOLCHAIN_FILE_aarch64-apple-darwin
  cargo:rerun-if-env-changed=CMAKE_TOOLCHAIN_FILE_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_CMAKE_TOOLCHAIN_FILE
  cargo:rerun-if-env-changed=CMAKE_TOOLCHAIN_FILE
  Initialized empty Git repository in /Users/user/RustroverProjects/primp/target/debug/build/boring-sys-imp-64af83603c90d862/out/boringssl/.git/
  cargo:warning=applying old ciphers patch to boringssl
  CMAKE_TOOLCHAIN_FILE_aarch64-apple-darwin = None
  CMAKE_TOOLCHAIN_FILE_aarch64_apple_darwin = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-apple-darwin = None
  CMAKE_GENERATOR_aarch64_apple_darwin = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_aarch64-apple-darwin = None
  CMAKE_PREFIX_PATH_aarch64_apple_darwin = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-apple-darwin = None
  CMAKE_aarch64_apple_darwin = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/Users/user/RustroverProjects/primp/target/debug/build/boring-sys-imp-64af83603c90d862/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/Users/user/RustroverProjects/primp/target/debug/build/boring-sys-imp-64af83603c90d862/out/boringssl" "-DCMAKE_OSX_ARCHITECTURES=arm64" "-DCMAKE_INSTALL_PREFIX=/Users/user/RustroverProjects/primp/target/debug/build/boring-sys-imp-64af83603c90d862/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC --target=arm64-apple-darwin -mmacosx-version-min=14.4" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC --target=arm64-apple-darwin -mmacosx-version-min=14.4" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC --target=arm64-apple-darwin -mmacosx-version-min=14.4" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
  --- stderr
  /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boring-sys-imp-4.9.3/patches/boringssl-old-ciphers.patch:25: trailing whitespace.
  /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boring-sys-imp-4.9.3/patches/boringssl-old-ciphers.patch:27: trailing whitespace.
  /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boring-sys-imp-4.9.3/patches/boringssl-old-ciphers.patch:58: trailing whitespace.
  /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boring-sys-imp-4.9.3/patches/boringssl-old-ciphers.patch:214: trailing whitespace.
  // 
  /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boring-sys-imp-4.9.3/patches/boringssl-old-ciphers.patch:219: trailing whitespace.
  //

**Comment by okeyzero** [comment]
<img width="1761" alt="image" src="https://github.com/user-attachments/assets/37af9742-b058-43e0-b763-024eb7988afc">

**Comment by deedy5** [comment]
OS?

**Comment by okeyzero** [comment]
> OS?

macos 
MacBook Pro M1 Max

**Comment by deedy5** [comment]
https://github.com/google/boringssl/blob/master/BUILDING.md#build-prerequisites

**Comment by okeyzero** [comment]
> https://github.com/google/boringssl/blob/master/BUILDING.md#build-prerequisites

 I executed the following commands
'git clone "https://boringssl.googlesource.com/boringssl"'
'cmake -GNinja -B build -DCMAKE_BUILD_TYPE=Release'
'ninja -C build'
Then I build my own project again, and it still fails.

I think I need to add the compiled boringssl to the environment variable, but I didn't get the correct way to deal with it in Google search.

**Comment by deedy5** [comment]
> https://github.com/google/boringssl/blob/master/BUILDING.md#build-prerequisites

`Compilers for C11 and C++14, or later, are required`

**Comment by okeyzero** [comment]
> > https://github.com/google/boringssl/blob/master/BUILDING.md#build-prerequisites
> 
> 
> 
> `Compilers for C11 and C++14, or later, are required`

I successfully compiled boringssl, but I don't know how to use the compiled boringssl to compile this project.

**Comment by deedy5** [comment]
You can investigate how it is compiled:
https://github.com/deedy5/primp/blob/73742d337892c4d4c341db39a11aee5864020781/.github/workflows/CI.yml#L170-L206

**Comment by deedy5** [comment]
Instruction:
```python
git clone https://github.com/deedy5/primp.git
cd primp
python3 -m venv .venv
source .venv/bin/activate
pip install maturin
maturin develop --release  
# Compiled library will be here: .venv/lib/python3.1x/site-packages
```
