### ISSUE TITLE
Provide an Environment Variable for CA Certificates

### ISSUE THREAD

**Issue by Alberto706** [deedy5/primp#48]
The PRIMP library currently does not provide an environment variable to specify the CA Certificates. This feature is essential for configuring secure HTTP connections, similar to what other Python HTTP clients offer. Adding this capability would enhance the flexibility and security of the library.

**Comment by deedy5** [comment]
Fixed in v0.8.0
Use `CA_CERT_FILE` env var to provide CA Certificates:
```python
export CA_CERT_FILE="/home/user/cert.pem"
```
