### ISSUE TITLE
TypeError: argument 'json': 'str' object cannot be converted to 'PyDict'

### ISSUE THREAD

**Issue by farukekim** [deedy5/primp#53]
Could you please fix this error? Using primp v0.8.1 and this post request is not working. Tried json.dumps(payload) and tried data=json_data and still same.
headers = {
        'Content-Type': 'application/json; charset=UTF-8',
        'Accept-Encoding': 'gzip',
        'User-Agent': 'okhttp/5.0.0'
    }

client = primp.Client(impersonate="okhttp_5", verify=False)
payload = [{'cropped_image': {'filename': 'ASCE57E9-D0E4-4B13-8350-DFAC7DB92EE9-cropped-image.jpg', 'media_type': 1, 'photo_crop_type': 1}, 'original_image': {'filename': 'ASCE57E9-D0E4-4B13-8350-DFAC7DB92EE9.jpg', 'media_type': 1, 'old_photo_filename': '', 'photo_crop_original_file_name': ''}}]
json_data = json.dumps(payload)
response = client.post('https://testapi.com/v2/upload_photos', headers=headers, json=json_data)

**Comment by deedy5** [comment]
try It: https://github.com/deedy5/primp/actions/runs/12146198321

**Comment by deedy5** [comment]
fixed in v0.8.2
